package com.ailawyer.backend.dashboard.entity;
import jakarta.persistence.*;
import lombok.*;

import java.time.OffsetDateTime;

@Builder
@AllArgsConstructor
@NoArgsConstructor
@Data
@Entity
@Table(name = "user")

//create table public."User" (
//user_id bigint generated by default as identity not null,
//password character varying(100) not null,
//nickname character varying(10) not null,
//email character varying(20) not null,
//constraint User_pkey primary key (user_id)
//) TABLESPACE pg_default;

public class UserEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "user_id")
    private Integer userId; // PK
    @Column(name = "password")
    private String password;
    @Column(name = "nickname")
    private String nickname;
    @Column(name = "email")
    private String email;
}
